name: style-check
on:
  pull_request:
  push:

jobs:
  styleCheck:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          dry: true
          prettier_options: --write **/*.{tsx,ts}
          working_directory: src/
