on:
  pull_request_target:
    types:
      - closed

jobs:
  update-preview-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: morbalint/git-merge-action@v1
        if: ${{ github.head_ref == 'preview' && github.base_ref == 'main' && github.event.pull_request.merged == true}}
        with:
          target: 'preview'
